version: '3.9'

services:
  greater-grades-react-app:
    container_name: greater-grades-react-app
    image: greater-grades-front-end
    environment:
      - CHOKIDAR_USEPOLLING=true  
      - BROWSER=none
      - NODE_ENV=development
    build: 
      context: ./UI
      dockerfile: DockerFile_UI
      target: development
    volumes: 
      - ./UI:/app
      - /app/node_modules
    ports:
      - 3000:3000

  greater-grades-web-api:
    container_name: greater-grades-web-api-container
    image: greater-grades-back-end
    build:
      context: ./Api
      dockerfile: DockerFile_API
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:5555
      MSSQL_SA_PASSWORD: NotPassword123!
    depends_on:
      - greater-grades-sqlserver    

  greater-grades-sqlserver:
    container_name: greater-grades-sqlserver-container
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=NotPassword123!
    ports:
      - "1633:1433"