FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER app
WORKDIR /app
EXPOSE 80
EXPOSE 443
EXPOSE 442
EXPOSE 5555

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["GreaterGradesBackend.Api/GreaterGradesBackend.Api.csproj", "GreaterGradesBackend.Api/"]
RUN dotnet restore "./GreaterGradesBackend.Api/GreaterGradesBackend.Api.csproj"
COPY . .
WORKDIR "/src/GreaterGradesBackend.Api"
RUN dotnet build "./GreaterGradesBackend.Api.csproj" -c Debug -o /app/build

FROM build AS publish
RUN dotnet publish "./GreaterGradesBackend.Api.csproj" -c Debug -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "GreaterGradesBackend.Api.dll"]